### PR TITLE
[non-unicode] less strict QuantifierPrefix parsing

### LINKED ISSUE #53: non-unicode compliance, part b50b69c9
youtube strikes again with this new regex:
```js
/(')'("{((),))(,)/
```

error message: `SyntaxError: failed to create matcher: Invalid quantifier`

putting it here so I don't lose it, gonna look into it tomorrow

### PR DESCRIPTION
**Pull request by selfisekai**
closes #53 

I don't see a way to make it good without refactoring the whole parser

### CODE REVIEW

File: tests/tests.rs [hunk 1]
```diff
@@ -1268,12 +1290,13 @@ fn property_escapes_invalid() {
     test_parse_fails(r#"\p{Line_Breakz=WAT}"#);
     test_parse_fails(r#"\P{Line_Breakz=Alphabetic}"#);
     test_parse_fails(r#"\p{Line_Breakz=Alphabetic}"#);
-    test_parse_fails(r#"\\P{General_Category=WAT}"#);
-    test_parse_fails(r#"\\p{General_Category=WAT}"#);
-    test_parse_fails(r#"\\P{Script_Extensions=H_e_h}"#);
-    test_parse_fails(r#"\\p{Script_Extensions=H_e_h}"#);
-    test_parse_fails(r#"\\P{Script=FooBarBazInvalid}"#);
-    test_parse_fails(r#"\\p{Script=FooBarBazInvalid}"#);
+    // should only fail with unicode flag
```
Comment (ridiculousfish) [inline tests/tests.rs:1293]: We should retain these tests but conditionalize them on Unicode.

File: src/parse.rs [hunk 2]
```diff
@@ -563,10 +563,23 @@ where
                 }))
             }
             Some('{') => {
+                // if parsed input is actually invalid, keep the previous one for rollback
```
Comment (ridiculousfish) [inline src/parse.rs:566]: The approach looks good to me but I think this can be simplified by factoring out the quantifier parsing. Today that is inline inside `try_consume_quantifier_prefix`; but it can be factored into a separate function, allowing the call site to branch on Unicode or not. So this code could look like so:

    if let Some(quantifier) = self.try_consume_braced_quantifier() {
          // Success
    } else if self.flags.unicode {
         return error("Invalid quantifier");
    } else {
        return Ok(None);
    }

File: tests/tests.rs [hunk 3]
```diff
@@ -303,11 +303,33 @@ fn run_misc_tests_tc(tc: TestConfig) {
         vec![Some("baaabaac"), Some("ba"), None, Some("abaac")]
     );
     tc.compilef(r"\0", "").match1f("abc\0def").test_eq("\0");
+}
 
-    assert_eq!(
-        tc.compilef(r";'()([/,-6,/])()]", "").match1_vec(";'/]"),
-        vec![Some(";'/]"), Some(""), Some("/"), Some("")]
-    );
+#[test]
```
Comment (ridiculousfish) [inline tests/tests.rs:308]: Cool new tests!

**Review by ridiculousfish — CHANGES_REQUESTED** [review]

**Comment by ridiculousfish** [comment]
Thank you for the contribution! I have some suggestions for refactoring but it's looking solid overall.

**Comment by ridiculousfish** [comment]
Thank you!
